# Generated by Django 4.2.4 on 2023-08-28 06:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areacode', models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(7)])),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CarDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealermobile', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(13)])),
                ('dealerwallet', models.IntegerField(default=0)),
                ('dealer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dealerarea', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='client.area')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclename', models.CharField(max_length=20)),
                ('vehiclemodel', models.CharField(max_length=20)),
                ('vehicleyear', models.DateField()),
                ('vehiclecapacity', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('vehiclecostperday', models.CharField(max_length=50)),
                ('vehicledescription', models.TextField()),
                ('vehiclelike', models.IntegerField(default=0)),
                ('vehiclearea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.area')),
                ('vehicledealer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.cardealer')),
            ],
        ),
    ]
